YoutubeDownloader/urls.py
from django.urls import path

from . import views

app_name = 'YoutubeDownloader'
urlpatterns = [
    #homepage
    path('', views.index, name='index'),
    path('task/', views.task, name='task'),
    path('new_task/', views.new_task, name='new_task'),
    path('download_task/', views.download_task, name='download_task')
]

YoutubeDownloaderX/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('YoutubeDownloader.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
"""Defines URL patterns for users""" 

from django.urls import path, include

from . import views

app_name = 'users' 
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),

    # Registration page.
    #path('register/', views.register, name='register'),
]

YoutubeDownloader/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    """The url or keyword the user is going to download."""
    content = models.TextField()
    email = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        """Return a string representation of the model.""" 
        return self.content

users/models.py
from django.db import models

# Create your models here.

YoutubeDownloader/forms.py
from django import forms
from .models import Task
class TaskForm(forms.ModelForm): 
    class Meta:
        model = Task
        fields = ['content', 'email']
        labels = {'content': '', 'email':''}

YoutubeDownloader/views.py
import os
from importlib.resources import contents
from importlib.util import resolve_name
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


from .videoprocess import download_video
from .models import Task
from .forms import TaskForm

@login_required
def index(request):
    """The home page for YoutubeDownloadX."""
    return render(request, 'YoutubeDownloader/index.html')

@login_required
def task(request):
    """Show a single task"""
    task = Task.objects.filter(owner=request.user)
    context = {'task': task}
    return render(request, 'YoutubeDownloader/task.html', context)

@login_required
def new_task(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TaskForm()
    else:
        # POST data submitted; process data.
        form = TaskForm(data=request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            return redirect('YoutubeDownloader:task')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'YoutubeDownloader/new_task.html', context)

@login_required
def download_task(request):
    tasks = Task.objects.filter(owner=request.user)
    if not os.path.exists("data/"):
        print("make data dir")
        os.makedirs("data/")
    if not os.path.exists(f"data/{request.user}/"):
        os.mkdir(f"data/{request.user}/")
        print("make user dir")
    if len(tasks) == 0:
        return redirect('YoutubeDownloader:task')
    download_video([str(task) for task in tasks], f"{request.user}", Task.objects.first().email)
    tasks.delete()
    return render(request, 'YoutubeDownloader/download_video.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('learning_logs:index')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

YoutubeDownloader/templates/YoutubeDownloader/base.html
<p>
    <a href="{% url 'YoutubeDownloader:index' %}">YoutubeDownloaderX</a> - 
    <a href="{% url 'YoutubeDownloader:task' %}">task</a> - 
    <a href="{% url 'YoutubeDownloader:new_task' %}">new_task</a> - 
    <a href="{% url 'YoutubeDownloader:download_task' %}">download_task</a> - 
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

YoutubeDownloader/templates/YoutubeDownloader/download_video.html
{% extends "YoutubeDownloader/base.html" %}

{% block content %}
    <p>Video {{ video_name }} is already download.</p>
{% endblock content %}

YoutubeDownloader/templates/YoutubeDownloader/index.html
{% extends "YoutubeDownloader/base.html" %}

{% block content %}
    <p>YoutubeDownloaderX help you download the videos on youtube.</p>
{% endblock content %}

YoutubeDownloader/templates/YoutubeDownloader/new_task.html
{% extends "YoutubeDownloader/base.html" %}

{% block content %}
    <p>Start a new task:(the next form is the email which the video send)</p>
    <form action="{% url 'YoutubeDownloader:new_task' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add task</button>
    </form>
    
{% endblock content %}

YoutubeDownloader/templates/YoutubeDownloader/task.html
{% extends "YoutubeDownloader/base.html" %}

{% block content %}
    <p>{{ task }}</p>
{% endblock content %}